### PR TITLE
docs: add basic verbiage and link to new GH security report

### LINKED ISSUE #1: [Docs]: SECURITY.md should capture more details around how we prefer bugs to be reported
The current `SECURITY.md` file is more a placeholder than anything. I looked across our repos and the only `SECURITY.md` files I found are in repos that are supported under the HackerOne program and so they will not be reusable across our other repos.

This file should probably contain information on the following things:
- Guidelines for reporting a security related issue for any severity
- How to actually report a security related issue
- Report template
- Reasonable expectations around our response time

We could probably use a template file found online and/or reach out to Amulet for some ideas on what this file should look like.

### PR DESCRIPTION
**Pull request by beckettsean**
Grabbed an example from https://github.com/electron/electron/blob/main/SECURITY.md as linked to from https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository.

Personalized for SL and removed some things that we don't yet have or aren't yet relevant. 

Clicking the [new](https://github.com/strangelove-ventures/oss-repo-template-golang/security/advisories/new) security report opens the standard GH reporting flow. 

Example of the basics
Screenshot 2024-05-29 at 14 33 36

closes #1

### CODE REVIEW

**Comment by beckettsean** [comment]
Unclear to me why relative link in the file is failing. Should be correct according to Markdown, unless I'm getting the path wrong.

Also note that we no longer mention `security@strange.love` in the file. The template I copied didn't have an email disclosure route, but maybe we want to keep one in there? I'm good either way.

**Comment by jtieri** [comment]
> Unclear to me why relative link in the file is failing. Should be correct according to Markdown, unless I'm getting the path wrong.
> 
> Also note that we no longer mention `security@strange.love` in the file. The template I copied didn't have an email disclosure route, but maybe we want to keep one in there? I'm good either way.

It looks like the relative path from this branch doesn't work but it may work once this is merged into main. One thing that isn't clear to me is how we end up being notified when someone reports a bug this way, do we just receive a notification in GitHub or will we also receive an email alert? Also does this report become visible to anyone or only our team?

**Comment by beckettsean** [comment]
Branches and relative paths not working totally makes sense. Thanks for that insight.

The security reporting feature is specific to GH: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

We should pick a public repo where we can experiment with the private reporting flow. Maybe something low traffic like `bech32cli` or `paramauthority`? Let's pick a repo and then I'll enable private reporting and submit a test.

**Comment by jtieri** [comment]
> Branches and relative paths not working totally makes sense. Thanks for that insight.
> 
> The security reporting feature is specific to GH: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository
> 
> We should pick a public repo where we can experiment with the private reporting flow. Maybe something low traffic like `bech32cli` or `paramauthority`? Let's pick a repo and then I'll enable private reporting and submit a test.

Yeah let's try with `bech32cli`

**Comment by beckettsean** [comment]
I enabled the private advisory feature for `bech32cli`, but unfortunately the submission workflow is not visible to me as an admin of the repo. I see the "New draft security advisory" button to make a new announcement, rather than the "Report a vulnerability" button other folks would see. 

Logged in as `slengci`, a non-repo admin, and submitted an example vuln report.

**Comment by beckettsean** [comment]
`bdch32cli` has [`eng-general-maintainers`](https://github.com/orgs/strangelove-ventures/teams/eng-general-maintainers) with Maintain access, and [`eng-general-admins`](https://github.com/orgs/strangelove-ventures/teams/eng-general-admins) with Admin access.

I suspect Admins get the notice, which would be @jtieri @agouin and @beckettsean.

**Comment by beckettsean** [comment]
What the submitter sees: 
Screenshot 2024-05-31 at 10 18 19
Screenshot 2024-05-31 at 10 18 24

The `slengci` user login info is available in 1Password if folks want to engage with the reporting flow from the submitter's side.

**Comment by beckettsean** [comment]
Note that I see no notifications yet to my personal or work email about this vuln. Unclear to me how we are notified about incoming reports if Admins don't get a push email notice.

**Comment by jtieri** [comment]
Hmm okay so the general flow does seem nice and I did get a notification on GitHub about the vulnerability, but yeah i would agree that it seems important to ensure the appropriate maintainers/admins are configured for all of our repos and that the appropriate settings are enabled to explicitly receive email notifications.

Here is what the notification looks like on GitHub
Screenshot 2024-05-31 at 3 02 44 PM

---

I just did some digging and it seems like to receive email notifications you have to do two things.

First you need to go into the repo that you want to receive email notifications for and click the `Watch` drop down menu in the top right. You need to watch the repo, select the `Custom` events option, and then select `Security alerts`

Screenshot 2024-05-31 at 3 14 39 PM

After that you need to go into your account settings and go into the `Notifications` sections and ensure that for `Participating, @mentions, and custom` you have `Notify me: on email` selected.

Screenshot 2024-05-31 at 3 15 01 PM

This would then enable email notifications for security alerts, @mentions, and conversations you are participating in. That doesn't seem to be too much noise you are receiving in email but it does require us to explicitly enable these alerts for every repo.

I submitted another security vulnerability report from the `slengci` account after that and I did receive an email notification this time.

Screenshot 2024-05-31 at 3 19 57 PM

I think that we can probably merge this PR and create another ticket somewhere (maybe mandrake or engineering-internal?) to make sure that we enable email notifications for security alerts in all of our repos. Maybe we should still include the `security@strange.love` email in the `SECURITY.md` file with a sentence stating sending an email is a secondary option but should only be used if a security vulnerability report has been submitted but the team has not responded within 48 hours or something along those lines. What do you think?

**Comment by beckettsean** [comment]
> I think that we can probably merge this PR 

agreed 

> and create another ticket somewhere (maybe mandrake or engineering-internal?) to make sure that we enable email notifications for security alerts in all of our repos. 

https://github.com/strangelove-ventures/compliance/issues/13

> Maybe we should still include the security@strange.love email in the SECURITY.md file

agreed, and I think we don't need to qualify it. Let's see what our signal volume is before we get too fancy with shaing the inputs.

**Review by jtieri — APPROVED** [review]

**Pull request merged**
